language: python
python: "3.6"

sudo: required

services:
  - docker

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 

jobs:
  include:
    - stage: test
    - script: ignore
    - stage: build
    - script: ./build awscli
    - script: ./build kubectl


notifications:
  slack: ngineered:EIKJFrzibOe0TwUhLXNe8Q2Q
