language: python
python: "3.6"

sudo: required

services:
  - docker

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 

jobs:
  include:
    - stage: build-awscli
      script: ./build awscli
    - stage: build-aws-shell
      script: ./build aws-shell
    - stage: build-kubectl
      script: ./build kubectl
    - stage: build-helm
      script: ./build helm
    - stage: build-serverless
      script: ./build serverless
    - stage: build-terraform
      script: ./build terraform
    - stage: build-vault
      script: ./build vault

notifications:
  slack: ngineered:EIKJFrzibOe0TwUhLXNe8Q2Q
