services:
  - docker

before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 

script:
  - for rel in `cat releases`; do export serverless_ver="${rel}" && docker build --build-arg SERVERLESS_VERSION="${serverless_ver}" -t "richarvey/serverless:${serverless_ver}" . ; done
  - for rel in `cat releases`; do export serverless_ver="${rel}" && docker push "richarvey/serverless:${serverless_ver}" ; done
  - latest=`cat latest` && docker tag richarvey/serverless:${latest} richarvey/serverless:latest && docker push "richarvey/serverless:latest"


notifications:
  slack: ngineered:EIKJFrzibOe0TwUhLXNe8Q2Q
